### ISSUE TITLE
Multi-person case

### ISSUE THREAD

**Issue by EvgeniaKomleva** [ArashHosseini/3d-pose-baseline#14]
@ArashHosseini 
Hi, can we use that code for multi-person case?
Why i get that [animation](https://drive.google.com/file/d/1YIFt8wReHZQdOLq2PLdCVGAqpHgIjM5s/view?usp=sharing) for [video](https://drive.google.com/file/d/1ZQnyWoC-f8I7NJyHrMrSxgutRXyVr-uo/view?usp=sharing)

**Comment by ArashHosseini** [comment]
hi @EvgeniaKomleva, here you [go](https://github.com/miu200521358/VMD-3d-pose-baseline-multi)

**Comment by EvgeniaKomleva** [comment]
Thanks!
