### ISSUE TITLE
Unable to download Human3.6m dataset

### ISSUE THREAD

**Issue by alberttjc** [ArashHosseini/3d-pose-baseline#16]
Great work man!

I have some issues downloading the human3.6m dataset. I had sent them an email requesting for member access however the email did not exist. Would you be able to guide me where I am able to find this dataset by any chance? Alternatively, would you be able to supply the pre-trained model?

Hope to hear from you soon!

**Comment by Aliiiu** [comment]
pls if you were able to get a solution to this pls share

**Comment by ycj1124** [comment]
did U find the solution ?

**Comment by ycj1124** [comment]
> pls if you were able to get a solution to this pls share

sorry to bother ,but did you get a solution now?

**Comment by Aliiiu** [comment]
> > pls if you were able to get a solution to this pls share
> 
> sorry to bother ,but did you get a solution now?

No I wasn't

**Comment by alberttjc** [comment]
Apologies, I forgot to reply. No one ever replied to me regarding this either.

**Comment by ycj1124** [comment]
alright，thx.by the way ,do you have any method using openpose by 3D model?
actually I am a student working on CV and my supervisor wants me to use openpose to track the body pose so as to track the arms in Chinese writing.Sounds like you wave your arms and it will recognize your tracking and show letters in chinese.But my capacity is not enough,so I am really under a lot of pressure now.After all,I have to finish my study and graduate. I would be really appreciated if you could give me some help.



发自我的iPhone


------------------ Original ------------------
From: Albert Tan ***@***.***&gt;
Date: Thu,Jun 17,2021 7:38 PM
To: ArashHosseini/3d-pose-baseline ***@***.***&gt;
Cc: ycj1124 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [ArashHosseini/3d-pose-baseline] Unable to download Human3.6m dataset (#16)





 
Apologies, I forgot to reply. No one ever replied to me regarding this either.

**Comment by ycj1124** [comment]
alright，thx.by the way ,do you have any method using openpose by 3D model?
actually I am a student working on CV and my supervisor wants me to use openpose to track the body pose so as to track the arms in Chinese writing.Sounds like you wave your arms and it will recognize your tracking and show letters in chinese.But my capacity is not enough,so I am really under a lot of pressure now.After all,I have to finish my study and graduate. I would be really appreciated if you could give me some help.




发自我的iPhone


------------------ Original ------------------
From: Aliiiu ***@***.***&gt;
Date: Thu,Jun 17,2021 2:39 PM
To: ArashHosseini/3d-pose-baseline ***@***.***&gt;
Cc: ycj1124 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [ArashHosseini/3d-pose-baseline] Unable to download Human3.6m dataset (#16)





   
pls if you were able to get a solution to this pls share
  
sorry to bother ,but did you get a solution now?
  
No I wasn't

**Comment by ArashHosseini** [comment]
@alberttjc to get the Human3.6m dataset, follow the instruction at section 3 [here](https://github.com/una-dinosauria/3d-pose-baseline)

> Go to http://vision.imar.ro/human3.6m/, log in, and download the D3 Positions files for subjects [1, 5, 6, 7, 8, 9, 11], and put them under the folder data/h36m. Your directory structure should look like this ...

update me pls if you cant solve the issue
