### ISSUE TITLE
About h36m.zip

### ISSUE THREAD

**Issue by er778899789** [ArashHosseini/3d-pose-baseline#6]
Sorry to bother you!!
I want to download the h36m.zip from the DropBox link which you offer,but the link was not alive.
Can you offer me the new link to get h36m.zip? Please, I really this to study my research.
Thank you!!

**Comment by ArashHosseini** [comment]
@er778899789 sorry but i can’t help you with that one. The link is not more valid since commit ea8bb79836e5c4f9afe33f4b9dfd4cab072f11c3
