### ISSUE TITLE
Accuracy of 3D coordinates on own images without tuning the model 

### ISSUE THREAD

**Issue by kaurrachneet6** [ArashHosseini/3d-pose-baseline#7]
If I have computed the 2D coordinates in pixels using my own camera and then used your code to compute 3D coordinates in cm (in camera coordinates) without tuning the model, i.e. I used your code directly to infer 3D points (because in my data, actual 3D coordinates are unknown and hence, I cannot tune the model). Would this method still give me correct 3D coordinates in cm? Or will it not, because my camera is different than what was used for training the model. Thanks.

**Comment by ArashHosseini** [comment]
Hi @kaurrachneet6 
author response https://github.com/una-dinosauria/3d-pose-baseline/issues/173
